version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-package-{{ checksum "package-lock.json" }}'
      - run: npm install
      - save_cache:
          key: 'v1-package-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run: npm run generate
      - persist_to_workspace:
          root: /home/circleci/app
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - attach_workspace:
          at: /home/circleci/app
      - firebase-deploy/deploy:
          token: $FIREBASE_DEPLOY_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
